server:
  port: 18080
logging:
    level.org.springframework: DEBUG
  #springboot   mybatis
  #jiazai mybatis peizhiwenjian
mybatis:
  mapper-locations: classpath:templates/mapper/*Mapper.xml
  config-location: classpath:config/sqlMapConfig.xml
  type-aliases-package: com.springboot.demo.model

#shujuyuan
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.115.216:13306/myProject?useUnicode=true&characterEncoding=utf-8
    username:  root
    password:  1228
  thymeleaf:
   cache: false # 开发时关闭缓存,不然没法看到实时页面
   mode: HTML # 用非严格的 HTML
   encoding: UTF-8
   servlet:
    content-type: text/html

#Demo 测试获取springboot Environment的数据，即配置文件的数据值
test:
  userName: 陈杰
  age: 21